filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

setup.kibana:
  host: "localhost:5601"
  username: "elastic"
  password: ${ELASTIC_PASSWORD}

output.logstash:
  hosts: ["logstash:5044"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
