version: '3.3' # specify docker-compose version

networks:
  server-mongo:
    driver: bridge # specify the network driver
  server-client:
    driver: bridge # specify the network driver
  elk:
    driver: bridge # specify the network driver


services:
  server:
    container_name: server_dev # name of the container
    build: ./server # specify the directory of the Dockerfile
    env_file:
      - .env.dev
    networks:
      - server-mongo # attach the server to the server-mongo network
      - server-client # attach the server to the server-client network
    ports:
        - "${SERVER_PORT}:${SERVER_PORT}" # we are mapping port of our local machine to port of the Docker container
    volumes:
      - ./server:/usr/src/app # specify the directory of the application code
    depends_on:
      - mongo


  client:
    container_name: client_dev # name of the container
    build:
        context: ./client # specify the directory of the Dockerfile
        target: development
    networks:
      - server-client # attach the client to the server-client network
    env_file:
      - .env.dev
    ports:
      - "3001:3000" # we are mapping port 3001 of our local machine to port 3000 of the Docker container
    volumes:
      - ./client:/usr/src/app # specify the directory of the application code


  mongo:
    container_name: mongo_dev # name of the container
    image: mongo # specify image to build container from
    networks:
      - server-mongo # attach the server to the server-mongo network
    ports:
      - "27017:27017" # map port 27017
    volumes:
      - ./data:/data/db # specify the directory of the database data


  elasticsearch:
    container_name: elasticsearch_dev
    image: elasticsearch:8.9.1
    networks:
      - elk
    ports:
      - "9200:9200"
    volumes:
       - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
        - "discovery.type=single-node"

  kibana:
    container_name: kibana_dev
    image: kibana:8.9.1
    environment:
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
        KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    networks:
      - elk
    ports:
      - "5601:5601"
    volumes:
      - ./elk/kibana/data:/usr/share/kibana/data
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    container_name: logstash_dev
    image: logstash:8.9.1
    environment:
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk
    ports:
      - "5044:5044"
    volumes:
      - ./elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat_dev
    image: docker.elastic.co/beats/filebeat:8.9.1
    user: root
    environment:
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

