version: '3.3'

networks:
  server-client:
    driver: bridge
  server-mongo:
    driver: bridge
  elk:
    driver: bridge

services:
  server:
    container_name: server
    build: ./server
    env_file:
      - .env.prod
    networks:
      - server-client
      - server-mongo
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/usr/src/app
      - ./server/logs:/usr/src/app/logs

  client:
    container_name: client
    build: ./client
    env_file:
      - .env.prod
    networks:
      - server-client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    networks:
      - server-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    networks:
      - elk
    ports:
      - "9200:9200"
    volumes:
       - ./elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.13.0
    networks:
      - elk
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0-arm64
    networks:
      - elk
    ports:
      - "5601:5601"
    volumes:
      - ./kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.13.0
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash
